package an.gal.android.goodideanote.storage

import an.gal.android.goodideanote.data.Idea
import an.gal.android.goodideanote.storage.room.IdeaEntity

object IdeaMapper {

    internal fun toIdeaEntity(idea: Idea) = IdeaEntity(
        id = null,  // autogenerated primary key
        title = idea.title,
        text = idea.text,
        purposeId = idea.purposeId
    )

    internal fun toIdeaPresenter(ideaEntity: IdeaEntity) = Idea(
        id = ideaEntity.id?.toInt(),
        title = ideaEntity.title,
        text = ideaEntity.text,
        purposeId = ideaEntity.purposeId
    )

}

